# Generated by Django 2.1.4 on 2020-06-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.BinaryField(max_length=300)),
                ('albumname', models.CharField(max_length=50)),
                ('visibility', models.BooleanField()),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('totalsum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AlbumDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.BinaryField(max_length=300)),
                ('albumname', models.CharField(max_length=50)),
                ('pic_data', models.ImageField(upload_to='detail')),
                ('createtime', models.DateTimeField()),
                ('djangocreatetime', models.DateTimeField(auto_now_add=True)),
                ('upload_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
